# Install (or remove) the login autostart for the Pydantic AI Deep Research Agent.
#
#   .\install-autostart.ps1            install
#   .\install-autostart.ps1 -Uninstall remove
#
# Writes a tiny .vbs stub into the per-user Startup folder. The stub exists
# purely to launch PowerShell with a hidden window: a .ps1 or .bat in Startup
# flashes a console at every login, and -WindowStyle Hidden on powershell.exe
# still shows that flash. WScript.Shell's Run with intWindowStyle 0 does not.
#
# Per-user, so no admin rights and nothing that affects other accounts.

param([switch]$Uninstall)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$startupDir = [Environment]::GetFolderPath("Startup")
$stubPath = Join-Path $startupDir "Pydantic AI Deep Research Agent.vbs"

if ($Uninstall) {
    if (Test-Path $stubPath) {
        Remove-Item $stubPath -Force
        Write-Host "Removed $stubPath"
    } else {
        Write-Host "Nothing to remove: $stubPath does not exist."
    }
    exit 0
}

$autostart = Join-Path $projectRoot "autostart.ps1"
if (-not (Test-Path $autostart)) {
    throw "autostart.ps1 is missing from $projectRoot"
}

# The script path must be quoted -- the project lives under a folder whose name
# contains a space -- and inside a VBScript string literal a quote is written by
# doubling it. Single quotes here would make VBScript fail to parse the line at
# login, which is the one place nobody would see the error.
$command = 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""' + $autostart + '""'
$stub = @"
' Launches the Pydantic AI Deep Research Agent at login, with no console window.
' Generated by install-autostart.ps1 -- edit that, not this.
CreateObject("WScript.Shell").Run "$command", 0, False
"@

Set-Content -Path $stubPath -Value $stub -Encoding ASCII
Write-Host "Installed $stubPath"
Write-Host "The agent will start at your next login and open $([char]34)http://127.0.0.1:7860$([char]34) in your default browser."
Write-Host "Remove it with: .\install-autostart.ps1 -Uninstall"
